"""Curated German Xetra (.DE) seed for the paper scanner."""

from __future__ import annotations

# Liquid DAX / large MDAX names on Yahoo Finance (EUR). Not exhaustive.
GERMAN_XETRA_SEED: dict[str, dict[str, str]] = {
    "SAP.DE": {"sector": "technology", "exchange": "XETRA"},
    "SIE.DE": {"sector": "industrial", "exchange": "XETRA"},
    "ALV.DE": {"sector": "insurance", "exchange": "XETRA"},
    "DTE.DE": {"sector": "telecom", "exchange": "XETRA"},
    "MUV2.DE": {"sector": "insurance", "exchange": "XETRA"},
    "DBK.DE": {"sector": "banking", "exchange": "XETRA"},
    "DB1.DE": {"sector": "exchange", "exchange": "XETRA"},
    "BMW.DE": {"sector": "automotive", "exchange": "XETRA"},
    "MBG.DE": {"sector": "automotive", "exchange": "XETRA"},
    "VOW3.DE": {"sector": "automotive", "exchange": "XETRA"},
    "ADS.DE": {"sector": "apparel", "exchange": "XETRA"},
    "BAS.DE": {"sector": "chemicals", "exchange": "XETRA"},
    "BAYN.DE": {"sector": "pharma", "exchange": "XETRA"},
    "DPW.DE": {"sector": "logistics", "exchange": "XETRA"},
    "EOAN.DE": {"sector": "energy", "exchange": "XETRA"},
    "RWE.DE": {"sector": "energy", "exchange": "XETRA"},
    "IFX.DE": {"sector": "semiconductor", "exchange": "XETRA"},
    "SHL.DE": {"sector": "healthcare", "exchange": "XETRA"},
    "HEN3.DE": {"sector": "consumer", "exchange": "XETRA"},
    "BEI.DE": {"sector": "consumer", "exchange": "XETRA"},
    "CON.DE": {"sector": "automotive", "exchange": "XETRA"},
    "HEI.DE": {"sector": "materials", "exchange": "XETRA"},
    "MTX.DE": {"sector": "aerospace", "exchange": "XETRA"},
    "RHM.DE": {"sector": "defense", "exchange": "XETRA"},
    "AIR.DE": {"sector": "aerospace", "exchange": "XETRA"},
    "FRE.DE": {"sector": "healthcare", "exchange": "XETRA"},
    "FME.DE": {"sector": "healthcare", "exchange": "XETRA"},
    "SY1.DE": {"sector": "chemicals", "exchange": "XETRA"},
    "VNA.DE": {"sector": "real_estate", "exchange": "XETRA"},
    "HNR1.DE": {"sector": "insurance", "exchange": "XETRA"},
    "ENR.DE": {"sector": "energy", "exchange": "XETRA"},
    "ZAL.DE": {"sector": "retail", "exchange": "XETRA"},
    "P911.DE": {"sector": "automotive", "exchange": "XETRA"},
    "DTG.DE": {"sector": "automotive", "exchange": "XETRA"},
    "QIA.DE": {"sector": "biotech", "exchange": "XETRA"},
    "SRT3.DE": {"sector": "healthcare", "exchange": "XETRA"},
    "1U1.DE": {"sector": "telecom", "exchange": "XETRA"},
    "BNR.DE": {"sector": "chemicals", "exchange": "XETRA"},
    "PAH3.DE": {"sector": "automotive", "exchange": "XETRA"},
    "CBK.DE": {"sector": "banking", "exchange": "XETRA"},
}
